
country=$1
country=$(echo $country | sed "s/.*alger.*^$/DZA/i" <<< $country) # Algeria 
country=$(echo $country | sed "s/.*argent.*^$/ARG/i" <<< $country) # Argentina
country=$(echo $country | sed "s/^ar$/ARG/i" <<< $country) # Argentina
country=$(echo $country | sed "s/.*armeni.*^$/ARM/i" <<< $country) # Armenia
country=$(echo $country | sed "s/.*austral.*^$/AUS/i" <<< $country) # Australia
country=$(echo $country | sed "s/^au$/AUS/i" <<< $country) # Australia
country=$(echo $country | sed "s/^at$/AUT/i" <<< $country) # Austria
country=$(echo $country | sed "s/.*baham.*^$/BHS/i" <<< $country) # Bahamas
country=$(echo $country | sed "s/.*bangla.*^$/BGD/i" <<< $country) # Bangladesh
country=$(echo $country | sed "s/.*barbados.*^$/BRB/i" <<< $country) # Barbados
country=$(echo $country | sed "s/^be$/BEL/i" <<< $country) # Belgium
country=$(echo $country | sed "s/.*belg.*$/BEL/i" <<< $country) # Belgium
country=$(echo $country | sed "s/.*belarus.*^$/BLR/i" <<< $country) # Belarus
country=$(echo $country | sed "s/.*bermu.*^$/BMU/i" <<< $country) # Bermuda
country=$(echo $country | sed "s/.*boliv.*^$/BOL/i" <<< $country) # Bolivia
country=$(echo $country | sed "s/.*botsw.*^$/BWA/i" <<< $country) # Botswana
country=$(echo $country | sed "s/^br$/BRA/i" <<< $country) # Brazil
country=$(echo $country | sed "s/^bra[sz]il.*^$/BRA/i" <<< $country) # Brazil
country=$(echo $country | sed "s/.*brunei.*^$/BRN/i" <<< $country) # Brunei
country=$(echo $country | sed "s/.*bulgar.*^$/BGR/i" <<< $country) # Bulgaria
country=$(echo $country | sed "s/^$/CAN/i" <<< $country) # Canada
country=$(echo $country | sed "s/^BC$/CAN/i" <<< $country) # Canada
country=$(echo $country | sed "s/^can\?$/CAN/i" <<< $country) # Canada
country=$(echo $country | sed "s/^cana.*$/CAN/i" <<< $country) # Canada
country=$(echo $country | sed "s/.*ontario.*$/CAN/i" <<< $country) # Canada
country=$(echo $country | sed "s/.*oshawa.*$/CAN/i" <<< $country) # Canada
country=$(echo $country | sed "s/.*quebec.*$/CAN/i" <<< $country) # Canada
country=$(echo $country | sed "s/^ch$/CHL/i" <<< $country) # Chile
country=$(echo $country | sed "s/.*chile.*$/CHL/i" <<< $country) # Chile
country=$(echo $country | sed "s/.*china.*$/CHN/i" <<< $country) # China 
country=$(echo $country | sed "s/^cn$/CHN/i" <<< $country) # China
country=$(echo $country | sed "s/.*netherl.*$/NLD/i" <<< $country) # China 
country=$(echo $country | sed "s/^co$/COL/i" <<< $country) # Colombia
country=$(echo $country | sed "s/.*colomb.*$/COL/i" <<< $country) # Colombia
country=$(echo $country | sed "s/^cr$/CRI/i" <<< $country) # Costa Rica
country=$(echo $country | sed "s/.*costa ri.*$/CRI/i" <<< $country) # Costa Rica
country=$(echo $country | sed "s/^hr$/HRV/i" <<< $country) # Croatia
country=$(echo $country | sed "s/.*croatia.*$/HRV/i" <<< $country) # Croatia
country=$(echo $country | sed "s/^cuba$/CUB/i" <<< $country) # Cuba
country=$(echo $country | sed "s/.*cyprus.*$/CYP/i" <<< $country) # Cyprus
country=$(echo $country | sed "s/^cz$/CZE/i" <<< $country) # Czech Republic
country=$(echo $country | sed "s/.*czech.*$/CZE/i" <<< $country) # Czech Republic
country=$(echo $country | sed "s/^dk$/DNK/i" <<< $country) # Denmark
country=$(echo $country | sed "s/^denm.*$/DNK/i" <<< $country) # Denmark
country=$(echo $country | sed "s/.*ecuador.*$/ECU/i" <<< $country) # Ecuador
country=$(echo $country | sed "s/.*england.*$/GBR/i" <<< $country) # England
country=$(echo $country | sed "s/^de$/DEU/i" <<< $country) # Germany
country=$(echo $country | sed "s/^deutsch.*$/DEU/i" <<< $country) # Germany
country=$(echo $country | sed "s/.*german.*$/DEU/i" <<< $country) # Germany
country=$(echo $country | sed "s/.*egypt.*$/EGY/i" <<< $country) # Egypt
country=$(echo $country | sed "s/.*estonia.*$/LKA/i" <<< $country) # Estonia
country=$(echo $country | sed "s/^fi$/FIN/i" <<< $country) # Finland
country=$(echo $country | sed "s/.*finland.*$/FIN/i" <<< $country) # Finland
country=$(echo $country | sed "s/^fr$/FRA/i" <<< $country) # France
country=$(echo $country | sed "s/.*france.*$/FRA/i" <<< $country) # France
country=$(echo $country | sed "s/.*gambia.*$/GMB/i" <<< $country) # France
country=$(echo $country | sed "s/.*georgia.*$/GEO/i" <<< $country) # Georgia
country=$(echo $country | sed "s/.*ghana.*$/GHA/i" <<< $country) # Ghana
country=$(echo $country | sed "s/.*greece.*$/GRC/i" <<< $country) # Greece
country=$(echo $country | sed "s/.*greenla.*$/GRN/i" <<< $country) # Greenland
country=$(echo $country | sed "s/.*guam.*$/GUM/i" <<< $country) # Guam
country=$(echo $country | sed "s/.*guyana.*$/GUY/i" <<< $country) # Guyana
country=$(echo $country | sed "s/.*haiti.*$/HTI/i" <<< $country) # Haiti
country=$(echo $country | sed "s/.*hondur.*$/HND/i" <<< $country) # Honduras
country=$(echo $country | sed "s/.*hong k.*$/HKG/i" <<< $country) # Hong Kong
country=$(echo $country | sed "s/^hu$/HUN/i" <<< $country) # Hungary
country=$(echo $country | sed "s/.*hungar.*$/HUN/i" <<< $country) # Hungary
country=$(echo $country | sed "s/.*iceland.*$/ISL/i" <<< $country) # Iceland
country=$(echo $country | sed "s/.*indones.*$/IDN/i" <<< $country) # Indonesia
country=$(echo $country | sed "s/^india.*$/IND/i" <<< $country) # India
country=$(echo $country | sed "s/.*iran.*$/IRN/i" <<< $country) # Iran
country=$(echo $country | sed "s/.*ireland.*$/IRL/i" <<< $country) # Ireland
country=$(echo $country | sed "s/^is$/ISR/i" <<< $country) # Israel
country=$(echo $country | sed "s/.*isreal.*$/ISR/i" <<< $country) # Israel
country=$(echo $country | sed "s/.*jerusalem.*$/ISR/i" <<< $country) # Israel
country=$(echo $country | sed "s/.*israel.*$/ISR/i" <<< $country) # Israel
country=$(echo $country | sed "s/^it$/ITA/i" <<< $country) # Italy
country=$(echo $country | sed "s/.*ital.*$/ITA/i" <<< $country) # Italy
country=$(echo $country | sed "s/^jm$/JAM/i" <<< $country) # Jamaica
country=$(echo $country | sed "s/.*jamai.*$/JAM/i" <<< $country) # Jamaica
country=$(echo $country | sed "s/^jo$/JOR/i" <<< $country) # Jordan
country=$(echo $country | sed "s/.*jordan.*$/ITA/i" <<< $country) # Jordan
country=$(echo $country | sed "s/^ke$/KEN/i" <<< $country) # Kenya
country=$(echo $country | sed "s/.*kenya.*$/KEN/i" <<< $country) # Kenya
country=$(echo $country | sed "s/^jp$/JPN/i" <<< $country) # Japan
country=$(echo $country | sed "s/.*japan.*$/ITA/i" <<< $country) # Japan
country=$(echo $country | sed "s/.*korea.*$/KOR/i" <<< $country) # Korea
country=$(echo $country | sed "s/.*kuwait.*$/KWT/i" <<< $country) # Kuwait
country=$(echo $country | sed "s/^lv$/LVA/i" <<< $country) # Latvia
country=$(echo $country | sed "s/.*latvia.*$/LVA/i" <<< $country) # Latvia
country=$(echo $country | sed "s/^lb$/LBN/i" <<< $country) # Lebanon
country=$(echo $country | sed "s/.*lebanon.*$/LBN/i" <<< $country) # Lebanon
country=$(echo $country | sed "s/.*lithuan.*$/LTU/i" <<< $country) # Lithuania
country=$(echo $country | sed "s/.*luxemb.*$/LUX/i" <<< $country) # Luxembourg
country=$(echo $country | sed "s/.*macedonia.*$/MKD/i" <<< $country) # Macedonia
country=$(echo $country | sed "s/.*malta.*$/MLT/i" <<< $country) # Malta
country=$(echo $country | sed "s/.*moroc.*$/MAR/i" <<< $country) # Morocco
country=$(echo $country | sed "s/^mx$/MEX/i" <<< $country) # Mexico
country=$(echo $country | sed "s/.*mexico.*$/MEX/i" <<< $country) # Mexico
country=$(echo $country | sed "s/^nm$/NAM/i" <<< $country) # Nambia
country=$(echo $country | sed "s/.*nambia.*$/NAM/i" <<< $country) # Nambia
country=$(echo $country | sed "s/^nl$/NLD/i" <<< $country) # Netherlands
country=$(echo $country | sed "s/.*nederl.*$/NLD/i" <<< $country) # Netherlands
country=$(echo $country | sed "s/.*netherl.*$/NLD/i" <<< $country) # Netherlands
country=$(echo $country | sed "s/.*nepal.*$/NPL/i" <<< $country) # Nepal
country=$(echo $country | sed "s/.*caledonia.*$/NCL/i" <<< $country) # New Calendonia
country=$(echo $country | sed "s/^nz$/NZL/i" <<< $country) # New Zealand
country=$(echo $country | sed "s/.*zeala.*$/NZL/i" <<< $country) # New Zealand
country=$(echo $country | sed "s/.*zeala.*$/NZL/i" <<< $country) # New Zealand
country=$(echo $country | sed "s/.*aotearoa.*$/NZL/i" <<< $country) # New Zealand
country=$(echo $country | sed "s/.*nigeria.*$/NGA/i" <<< $country) # Nigeria
country=$(echo $country | sed "s/^no$/NOR/i" <<< $country) # Norway
country=$(echo $country | sed "s/.*pakist.*$/PAK/i" <<< $country) # Pakistan
country=$(echo $country | sed "s/.*papua.*$/PNG/i" <<< $country) # Papua New Guinea
country=$(echo $country | sed "s/.*paragu.*$/PRY/i" <<< $country) # Paraguay
country=$(echo $country | sed "s/.*peru.*$/PER/i" <<< $country) # Peru
country=$(echo $country | sed "s/.*philip.*$/PHL/i" <<< $country) # Philipinnes
country=$(echo $country | sed "s/^pl$/POL/i" <<< $country) # Poland
country=$(echo $country | sed "s/^pol$/POL/i" <<< $country) # Poland
country=$(echo $country | sed "s/.*poland.*$/POL/i" <<< $country) # Poland
country=$(echo $country | sed "s/^pt$/PRT/i" <<< $country) # Portugal
country=$(echo $country | sed "s/.*portug.*/PRT/i" <<< $country) # Portugal
country=$(echo $country | sed "s/.*puerto ri.*$/PRI/i" <<< $country) # Puero Rico
country=$(echo $country | sed "s/^ro$/ROU/i" <<< $country) # Romania
country=$(echo $country | sed "s/.*romani.*/ROU/i" <<< $country) # Romania
country=$(echo $country | sed "s/.*russia.*/RUS/i" <<< $country) # Russian Federation
country=$(echo $country | sed "s/.*marino.*$/SMR/i" <<< $country) # San Marino
country=$(echo $country | sed "s/.*saudi.*$/SAU/i" <<< $country) # Saudi Arabia
country=$(echo $country | sed "s/.*leone.*$/SLE/i" <<< $country) # Sierra Leone
country=$(echo $country | sed "s/^sg$/SGP/i" <<< $country) # Singapore
country=$(echo $country | sed "s/.*singapore.*$/SGP/i" <<< $country) # Singapore
country=$(echo $country | sed "s/^sk$/SVK/i" <<< $country) # Slovokia
country=$(echo $country | sed "s/.*slovak.*/SVK/i" <<< $country) # Slovokia
country=$(echo $country | sed "s/^si$/SVN/i" <<< $country) # Slovenia
country=$(echo $country | sed "s/.*slovenia*/SVN/i" <<< $country) # Slovenia
country=$(echo $country | sed "s/.*somalia*/SOM/i" <<< $country) # Somalia
country=$(echo $country | sed "s/.*south afr/ZAF/i" <<< $country) # South Africa
country=$(echo $country | sed "s/^es$/ESP/i" <<< $country) # Spain
country=$(echo $country | sed "s/^espan.*$/ESP/i" <<< $country) # Spain
country=$(echo $country | sed "s/^spain.*$/ESP/i" <<< $country) # Spain
country=$(echo $country | sed "s/.*ceylon.*$/LKA/i" <<< $country) # Sri Lanka
country=$(echo $country | sed "s/.*lanka.*$/LKA/i" <<< $country) # Sri Lanka
country=$(echo $country | sed "s/.*syria.*$/SYR/i" <<< $country) # Syria
country=$(echo $country | sed "s/^se$/SWE/i" <<< $country) # Sweden
country=$(echo $country | sed "s/.*suisse.*$/CHE/i" <<< $country) # Switzerland
country=$(echo $country | sed "s/.*switz.*$/CHE/i" <<< $country) # Switzerland
country=$(echo $country | sed "s/^ch$/CHE/i" <<< $country) # Switzerland
country=$(echo $country | sed "s/.*taiwan.*$/TWN/i" <<< $country) # Taiwan
country=$(echo $country | sed "s/.*tanzan.*$/TZA/i" <<< $country) # Tanzania
country=$(echo $country | sed "s/.*thaila.*$/THA/i" <<< $country) # Thailand
country=$(echo $country | sed "s/.*tunisia.*/TUN/i" <<< $country) # Tunisia
country=$(echo $country | sed "s/.*turkey.*/TUR/i" <<< $country) # Turkey
country=$(echo $country | sed "s/.*trinidad.*$/TTO/i" <<< $country) # Trinibad and Tobago
country=$(echo $country | sed "s/^gb$/UK/i" <<< $country) # UK
country=$(echo $country | sed "s/^uni[^ ]* \?k.*$/UK/i" <<< $country) # UK
country=$(echo $country | sed "s/^u[\. ]*k[\. ]*/UK/i" <<< $country) # UK
country=$(echo $country | sed "s/.*britain.*/UK/i" <<< $country) # UK
country=$(echo $country | sed "s/.*scotland.*/UK/i" <<< $country) # UK
country=$(echo $country | sed "s/.*ukrai.*/UKR/i" <<< $country) # UKR
country=$(echo $country | sed "s/.*urugua.*/URY/i" <<< $country) # Uruguay
country=$(echo $country | sed "s/^u[\. ]*s[\. ]*a[\. ]*/USA/i" <<< $country) # USA
country=$(echo $country | sed "s/^usd\?$/USA/i" <<< $country) # USA
country=$(echo $country | sed "s/^united sta.*/USA/i" <<< $country) # USA
country=$(echo $country | sed "s/.*[0-9][0-9][0-9][0-9].*/USA/i" <<< $country) # USA
country=$(echo $country | sed "s/.*reston.*/USA/i" <<< $country) # USA
echo $country
